/**
 * Player utilities for managing guest user information
 * Uses localStorage to persist guest user data across sessions
 * Guest username and nickname are generated by the backend
 */

const STORAGE_KEY = 'sudoku_guest_user';

/**
 * Get guest user information from localStorage
 * Returns null if no user is stored
 * @returns {Object|null} { id, username, nickname, isGuest } or null
 */
export function getGuestUser() {
    try {
        const stored = localStorage.getItem(STORAGE_KEY);
        if (stored) {
            const user = JSON.parse(stored);
            // Validate stored data
            if (user.id && user.username && user.nickname) {
                return user;
            }
        }
    } catch (error) {
        console.error('Error reading guest user from localStorage:', error);
    }

    // No user found in localStorage
    return null;
}

/**
 * Save guest user information to localStorage
 * @param {Object} user - User object with id, username, nickname, isGuest
 */
export function saveGuestUser(user) {
    try {
        const userData = {
            id: user.id,
            username: user.username,
            nickname: user.nickname,
            isGuest: user.isGuest !== undefined ? user.isGuest : true,
        };
        localStorage.setItem(STORAGE_KEY, JSON.stringify(userData));
    } catch (error) {
        console.error('Error saving guest user to localStorage:', error);
    }
}

/**
 * Get current player ID (for use in highscore API and game creation)
 * @returns {string|null} Player ID (MongoDB ObjectId as string) or null if not initialized
 */
export function getPlayerId() {
    const user = getGuestUser();
    return user ? user.id : null; // Use MongoDB ObjectId
}

/**
 * Get current player name (for display and highscore API)
 * @returns {string|null} Player name (nickname) or null if not initialized
 */
export function getPlayerName() {
    const user = getGuestUser();
    return user ? user.nickname : null;
}

/**
 * Clear guest user information from localStorage
 */
export function clearGuestUser() {
    try {
        localStorage.removeItem(STORAGE_KEY);
    } catch (error) {
        console.error('Error clearing guest user from localStorage:', error);
    }
}

